version: '3.8'
services:
  animated-train:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production  # Set environment variables as needed
    depends_on:
      - mongodb               # Ensure MongoDB starts before the application

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db # Persist MongoDB data

volumes:
  mongodb_data:              # Named volume for MongoDB data persistence
